### ISSUE TITLE
[Bug]: ESM format output is incorrect & auto detect entry file fails

### ISSUE THREAD

**Issue by ShaneYu** [web-infra-dev/rslib#162]
### Version

```sh
System:
    OS: Windows 11 10.0.22631
    CPU: (32) x64 AMD Ryzen 9 7950X 16-Core Processor
    Memory: 4.11 GB / 31.21 GB
  Browsers:
    Edge: Chromium (127.0.2651.86)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @rslib/core: ^0.0.2 => 0.0.2
```

### Details

There are currently two issues I am facing with Rslib at this time.

Rsbuild is meant to be able to automatically find the entry point via `src/index.ts` and a load of other file extensions, according to the error I get. Issue is that when using Rslib without specifying a `source.entry` in the config, it cannot locate the entry `src/index.ts` file that I have.

This results in the following error:

```
error   Failed to build.
error   Could not find any entry module, please make sure that src/index.(ts|js|tsx|jsx|mjs|cjs) exists,
        or customize entry through the source.entry configuration.
```

Entry config added to make it work:

```js
source: {
  entry: {
    index: './src/index.ts',
  },
},
```

Adding in the `source.entry` config resolves the above issue, then the second issue is that the ESM format output does not look correct. It only outputs `*.d.mts` file and no actual `*.mjs` files are created; this means that only type definitions exist and no actual code. Whereas the CJS format is correctly output `*.js` code files and also the `*.d.ts` type definition files.

![image](https://github.com/user-attachments/assets/b3f0eb8f-a2a4-484e-b81f-f8d2722115e8)

### Reproduce link

https://github.com/ShaneYu/rslib-esm-issue

### Reproduce Steps

To replicate these issues I have created a temp GitHub repository that can be cloned down and played with.

**For the second issue regarding  ESM format output being incorrect:**

1. Clone the repository with `git clone git@github.com:ShaneYu/rslib-esm-issue.git`
2. Install the dependencies with `pnpm install`
3. Run a build with `pnpm build`

Now go and look at the output files under `./dist/esm` you will notice that no `*.mjs` code files have been created, however the `*.mts` type definition files have been. The CJS output on the other hand, this has the expected code files and type definitions.

![image](https://github.com/user-attachments/assets/6a9eab4e-a6ab-4450-a1c0-6184632bb1e3)

**For the first issue regarding the entry point configuration:**

_Skip steps 1 and 2 if done previously._

1. Clone the repository with `git clone git@github.com:ShaneYu/rslib-esm-issue.git`
2. Install the dependencies with `pnpm install`
3. Edit the `rslib.config.ts` file to remove the `source.entry` config from both ESM and CJS lib configs
    ```js
    source: {
      entry: {
        index: './src/index.ts',
      },
    },
    ```

4. Run a build with `pnpm build`

Notice that despite having a `src/index.ts` file, it results in an error and states that the entry file cannot be found.

![image](https://github.com/user-attachments/assets/968a3f9d-91b6-43d8-8449-9da3dc9aa410)

**Comment by Timeless0911** [comment]
Can you upgrade `@rslib/core` to `0.0.4`, I think the two issues have been solved.

**Comment by ShaneYu** [comment]
@Timeless0911 Thank you, I can confirm that upgrading to `0.0.4` has indeed resolved both issues. 😁 

❤️ Thank you! 😄 Loving rslib so much! 😉
