### ISSUE TITLE
[Bug]: Rslib build breaks shebang line in bin file

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rslib#166]
### Version

```sh
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.72 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 128.0.6613.86
    Safari: 17.6
  npmPackages:
    @rslib/core: 0.0.4 => 0.0.4
```

### Details

Rslib build breaks shebang line in bin file:

- Input:

![image](https://github.com/user-attachments/assets/deb4aeb4-efc5-489c-b4b6-f42017a8350b)

- Output:

![image](https://github.com/user-attachments/assets/8f66d165-5b81-47f6-b90e-a2373cf3c6fe)

- Failed to run:

![image](https://github.com/user-attachments/assets/9562256e-9dfa-424f-86c2-a178644b05dc)

### Reproduce link

https://github.com/web-infra-dev/rsbuild/tree/8a2a850aad336b726e50b2b1bb203d8c72c1c48a/packages/create-rsbuild

### Reproduce Steps

1. pnpm i
2. pnpm build

**Comment by fi3ework** [comment]
- webpack / Rspack will adding `//` to strip the shebang, see https://github.com/webpack/webpack/pull/13961.
- webpack / Rspack will not hoist shebang to the top of the bundle intentionally.
- esbuild already handles chmod internally https://github.com/evanw/esbuild/commit/b808c0d905551dde55e2485eb18d488b12e4ba94.

Shortly we could use https://github.com/shuangwhywhy/webpack-shebang-plugin. In longterm, we could considering making this a built-in plugin to webpack/Rspack.

**Comment by chenjiahan** [comment]
Yes, we can add a built-in plugin to webpack and Rspack when the `target` is `node`.
