### ISSUE TITLE
[Bug]: Should remove the comments of types

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rslib#210]
### Version

```sh
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 67.81 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 128.0.6613.138
    Safari: 17.6
  npmPackages:
    @rslib/core: 0.0.6 => 0.0.6
```

### Details

- Input:

```ts
export type SomeType = {
  /**
   * @deprecated
   */
  foo?: {
    /**
     * @deprecated
     */
    bar: string;
  };
};

const foo = () => {};
```

- Current output:

```js
/**
 * @deprecated
 */
/**
 * @deprecated
 */
const foo = () => {};
```

- Expected output:

```js
const foo = () => {};
```

### Reproduce link

https://github.com/web-infra-dev/rsbuild/pull/3502

### Reproduce Steps

See https://github.com/web-infra-dev/rsbuild/pull/3502

**Comment by Timeless0911** [comment]
![image](https://github.com/user-attachments/assets/ddae91b7-89fd-4fbd-8307-61f6fdb4d630)

**Comment by fi3ework** [comment]
Related to https://swc.rs/docs/configuration/compilation#jscpreserveallcomments is turned on.

minimal repro: https://play.swc.rs/?version=1.7.26&code=H4sIAAAAAAAAA0utKMgvKlEoqSxIVQjOz00NATFsFaq5FBT0tbSApIKWgkNKakFRanJiSWoKWEAfSKbl59tbgZXBFWJRClWsoJCUWGSlUFxSlJmXbg0UqLXmAiKu5Py84hKQUUAbNTQVbO0UqmutAc2f9WSSAAAA&config=H4sIAAAAAAAAA1WOuwrDMAxF93xF0NyhZOxW%2BiXCKCFFfiCppSHk3yuH4Kabde6RfNeu7yHOaR4XuPUjstKloqcGn1d%2F%2BlCElORNd%2BZHjpGSqYcmr92tAooLbcGJLsnw4wRsKaRB5mKwh9uxYygTWTVIh%2BswwMFbmXYrYpqYzvV2PGaJaCfRWfjVA2SGI9n%2BfuactZ3rarp9Ae9Yl3MHAQAA

**Comment by Timeless0911** [comment]
This issue can be closed after https://github.com/web-infra-dev/rsbuild/pull/3510 merged and released.
