### ISSUE TITLE
[Feature]: Support for Module Federation

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rslib#212]
### What problem does this feature solve?

Allow Rslib to create Module Federation remote module.

### What does the proposed API look like?

I have created a demo (https://github.com/chenjiahan/rslib-mf) to try out the `ModuleFederationPlugin` in Rslib, and I find that the `format: 'esm'` breaks the output of Module Federation, so Rslib should provide a new format for Module Federation, such as `format: 'module-federation'` or `format: 'none'`.

**Comment by Timeless0911** [comment]
I prefer `format: 'module-federation'`, since `format: 'none'` seems a bit ambiguous.
