### ISSUE TITLE
[Feature]: Better log message when sass/less plugin is not installed

### ISSUE THREAD

**Issue by Timeless0911** [web-infra-dev/rslib#227]
### What problem does this feature solve?

Rslib supports using sass/less as css precessor, we should log some user-friendly error message if user do not install and configure`@rsbuild/plugin-less` / `@rsbuild/plugin-sass`.

### What does the proposed API look like?

-

**Comment by chenjiahan** [comment]
Rsbuild already provides logs for this case:

![image](https://github.com/user-attachments/assets/7a1470da-b3bb-4329-8ffd-e6e13010da36)

**Comment by Timeless0911** [comment]
My bad, didn't notice it at once😂
