### ISSUE TITLE
[Bug]: `__dirname` is broken when using `syntax: 'es2021'`

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rslib#236]
## Version

```sh
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.62 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 129.0.6668.59
    Safari: 17.6
```

### Input:

```js
console.log(__dirname);
```

### Without `syntax`

- config:

```js
import { defineConfig } from '@rslib/core';

export default defineConfig({
  lib: [{ format: 'esm' }],
  output: {
    target: 'node',
  },
});
```

- output:

```js
import { fileURLToPath as __webpack_fileURLToPath__ } from "url";
import { dirname as __webpack_dirname__ } from "path";
var __dirname = __webpack_dirname__(__webpack_fileURLToPath__(import.meta.url));
console.log(__dirname);
```

### With `syntax`

- config:

```js
import { defineConfig } from '@rslib/core';

export default defineConfig({
  lib: [{ format: 'esm', syntax: 'es2021' }],
  output: {
    target: 'node',
  },
});
```

- output:

```js
console.log('/');
```

## Reproduce link

https://github.com/web-infra-dev/rsbuild/pull/3563

## Reproduce Steps

See https://github.com/web-infra-dev/rsbuild/pull/3563

`create-rsbuild` is broken after adding `syntax: 'es2021'`.

**Comment by fi3ework** [comment]
Hmm, it's because we could `syntax` to `rspack.target` lately. And `es2021` is translated to following queries, when browser related query and node query present at the same time. Then `target.node` related config will not be applied anymore. 

```js
    es2021: {
      Chrome: '85.0.0',
      Edge: '85.0.0',
      Firefox: '79.0.0',
      iOS: '14.0.0',
      Node: '15.0.0',
      Opera: '71.0.0',
      Safari: '14.0.0',
    },
```

I'll fix this by preserving `esX` as it's a valid query for `rspack.target`.
