### ISSUE TITLE
[Bug]: Rslib failed to report the type errors

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rslib#283]
### Version

Rslib 0.0.11

### Details

See:

![Image](https://github.com/user-attachments/assets/f588e2cd-be05-4965-bb2b-10e16f597e4b)

### Reproduce link

https://github.com/web-infra-dev/rsbuild/pull/3691

### Reproduce Steps

1. cd packages/plugin-babel
2. pnpm build

**Comment by Timeless0911** [comment]
This may be the difference of Typescript Compiler API, running `pnpm build --watch` will throw these errors.

- `pnpm build`: `ts.createProgram`
- `pnpm build --watch`: `ts.createSemanticDiagnosticsBuilderProgram`
