### ISSUE TITLE
[Bug]: Dynamic import in CJS output is broken

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rslib#287]
### Version

Rslib 0.0.11

### Details

Dynamic import in CJS output is broken.

There are some conditions:

- Use dynamic import in the source code
- Output `cjs` format
- package.json contains `type: 'module'`

For example, the input code is:

```js
export async function main() {
  const { TsconfigPathsPlugin } = await import('tsconfig-paths-webpack-plugin');

  console.log(TsconfigPathsPlugin);
}

main();
```

Run the output code, and `console.log(TsconfigPathsPlugin);` get `undefined`.

### Reproduce link

https://github.com/chenjiahan/rslib-repro-dynamic-import-cjs-interop

### Reproduce Steps

- tsup: 

![Image](https://github.com/user-attachments/assets/a20aac0f-0e69-4b40-b5fb-3397ae4f87af)

- Modern.js Module:

![Image](https://github.com/user-attachments/assets/e0b01a09-78d8-4019-a058-1253bb74b6a8)

- Rslib:

![Image](https://github.com/user-attachments/assets/d78daf3a-11eb-4be9-834f-60bbd6d87e55)

**Comment by fi3ework** [comment]
Duplicated with https://github.com/web-infra-dev/rslib/issues/121.

Current workaround

```diff
  output: {
    target: 'node',
+    externals: {
+      'tsconfig-paths-webpack-plugin': 'import tsconfig-paths-webpack-plugin',
+    },
  },
```

**Comment by fi3ework** [comment]
It will be resolved when we implement external map for webpack and Rspack, we're already working on this.

**Comment by chenjiahan** [comment]
Close duplicated issue
