### ISSUE TITLE
Is it compatible with the configuration format of TSUP?

### ISSUE THREAD

**Issue by zhangfisher** [web-infra-dev/rslib#294]
### What problem does this feature solve?

The configuration format of TSUP looks very simple

### What does the proposed API look like?

tsup

**Comment by Timeless0911** [comment]
We support different configurations for each format, and it can be easily migrated from tsup.

**Comment by zhangfisher** [comment]
rslib seems to have not been released stably, and the configuration document is not available yet.

我想尝试一下用来打包我的库[autostore](https://github.com/zhangfisher/autostore)，tsup配置如下：

```ts
export default defineConfig( 
    {
        entry: [
            'src/index.ts'
        ],
        format: ['esm','cjs'],
        dts: true,
        splitting: true,
        sourcemap: true,
        clean: true,
        treeshake:true,  
        minify: true,
        noExternal:['flex-tools','mitt']
    }  )
 
```

对应的rslib配置应该是怎么样的？

**Comment by Timeless0911** [comment]
see https://lib.rsbuild.dev/guide/migration/tsup#configuration-migration

**Comment by fi3ework** [comment]
See https://lib.rsbuild.dev/guide/migration/tsup.

**Comment by linkb15** [comment]
@fi3ework how about treeshake:true? is there equivalent for it?

**Comment by fi3ework** [comment]
By default, Rslib enables tree shaking. Do you want to disable that?
