### ISSUE TITLE
[Bug]: Not split into a new chunk with dynamic import when bundling esm

### ISSUE THREAD

**Issue by Timeless0911** [web-infra-dev/rslib#31]
### Details

![image](https://github.com/web-infra-dev/rslib/assets/50201324/a6568a87-ae77-4ec5-8e30-b2903e90c388)

when comment `chunkFormat: 'module`, chunk has been splitted.

![image](https://github.com/web-infra-dev/rslib/assets/50201324/080f3637-a852-4bb7-a8c1-18d1837b90ac)

**Comment by fi3ework** [comment]
Not reproducible in 0.1.0. We can't recall the detailed issue then.
