### ISSUE TITLE
[Bug]: set the syntax es6, rspack not match the API schema

### ISSUE THREAD

**Issue by wChenonly** [web-infra-dev/rslib#322]
### Version

System:
    OS: macOS 15.0.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 2.27 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 130.0.6723.70
    Safari: 18.0.1
  npmPackages:
    @rslib/core: ^0.0.13 => 0.0.13 

### Details

When I set the syntax es6, I get the error

ValidationError: Invalid configuration object. Rspack has been initialized using a configuration object that does not match the API schema.

![Image](https://github.com/user-attachments/assets/81528a9d-ebb8-4e37-9777-95ae400fe256)

Do we need to remove `es6` to be consistent with `rspack`? 

Keep it consistent with the official ECMAScript `es2015`, which is `es6`

### Reproduce link

no

### Reproduce Steps

1. rsbuild.config.ts set syntax es6

```ts
// rsbuild.config.ts
import { defineConfig } from '@rslib/core'

export default defineConfig({
  lib: [
    {
      format: 'esm',
      syntax: 'es6',
      dts: { bundle: false }
    }
  ]
})

```
2. executive `npx rslib build`

**Comment by Timeless0911** [comment]
May be we can add an alias `es6 -> es2015`.

**Comment by fi3ework** [comment]
Thank you for reporting the bug. We have retained `"es6"` because most builds support it, even though it is just an outdated alias for `"es2015"`. This is an internal error, and we should map `"es6"` to `"es2015"` during the conversion. However, I believe we will still keep `"es6"`. cc @chenjiahan
