### ISSUE TITLE
[Bug]: performance.chunkSplit is not working for Node.js libraries

### ISSUE THREAD

**Issue by xc2** [web-infra-dev/rslib#354]
### Version

```
  System:
    OS: macOS 15.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 142.00 MB / 32.00 GB
    Shell: 3.7.1 - /opt/homebrew/bin/fish
  Browsers:
    Chrome: 130.0.6723.70
    Safari: 18.1
  npmPackages:
    @rslib/core: ^0.0.15 => 0.0.15
```

### rslib config

<details>
<summary>rslib.config.ts</summary>

```ts
import { defineConfig } from "@rslib/core";

export default defineConfig({
  output: { cleanDistPath: true },
  lib: [
    {
      format: "cjs",
      syntax: "es2021",
      dts: false,
      autoExternal: false,
      autoExtension: false,
      source: {
        entry: {
          bun: "./binary/bun.ts",
          node: "./binary/node.ts",
        },
      },
      performance: {
        chunkSplit: {
          strategy: "custom",
          splitChunks: {
            cacheGroups: {
              sources: {
                test: /./,
                name: "sources",
                enforce: true,
                chunks: "all",
                reuseExistingChunk: true,
              },
            },
          },
        },
      },
      output: {
        externals: {
          url: "node:url",
          buffer: "node:buffer",
          events: "node:events",
        },
        minify: true,
        cleanDistPath: false,
        target: "node",
        distPath: {
          root: "releases/binary",
          jsAsync: "internal",
        },
      },
    },
  ],
});
```

</details>

### Inspect

Only `chunks: 'async'` is in rspack config

```js
// rspack.config.mjs optimization.splitChunks
{ chunks: 'async' }
```

### Reproduce link

-

### Reproduce Steps

-

**Comment by fi3ework** [comment]
Seems like related to `output: node` https://github.com/fi3ework-reproduction/rslib-354/blob/main/rsbuild.config.mjs.

**Comment by chenjiahan** [comment]
Yes we should allow to manually configuring split chunks for the node target, let me think about how to allow it..

**Comment by chenjiahan** [comment]
For the node target, I think only splitting async chunks is allowed. If we split some initial chunks, HTML plugin can reload all of them, but Node package consumers can only import an entry module rather than import all initial modules.

For the web worker target, as far as I know, only `importScripts` is allowed to import other scripts, so chunk splitting never seems to work in the worker thread.

**Comment by chenjiahan** [comment]
I have added documentation the clarify the current behavior: https://github.com/web-infra-dev/rsbuild/pull/4088

This means that when `output.target` is `node` or `web-worker`,  Rsbuild's `performance.chunkSplit` will not take effect. If we change this default behavior, this may have unpredictable impacts on existing SSR projects.

Using `tools.rspack` should work if users need to split Node bundles:

```ts
export default {
  tools: {
    rspack: {
      optimization: {
        splitChunks: {
          // options
        },
      },
    },
  },
};
```
