### ISSUE TITLE
When you define an external rslib config file with the `-c` parameter, it can't find the package.json anymore.

### ISSUE THREAD

**Issue by fi3ework** [web-infra-dev/rslib#361]
When you define an external rslib config file with the `-c` parameter, it can't find the package.json anymore. For example:

```
rslib build -c ./etc/rsbuild/config.ts
```

It will complain that it can't find the package.json from the root folder.

_Originally posted by @binarykitchen in https://github.com/web-infra-dev/rslib/discussions/359_

**Comment by Timeless0911** [comment]
Maybe we should use `process.cwd()` as a fallback root path to load `package.json`.

**Comment by binarykitchen** [comment]
... and unit tests. What if rslib is called from a subdirectory where no config nor package.json exist?

**Comment by Timeless0911** [comment]
> ... and unit tests. What if rslib is called from a subdirectory where no config nor package.json exist?

You mean we need to find the closest config file / package.json from bottom to up? If so, `-c` parameter is not enough, and we also need a `--root` parameter to specify where `package.json` folder is.

**Comment by binarykitchen** [comment]
Well, too many parameters overcomplicate, which isn't good. Keep it simple. The `-c` parameter adds extra complexity.

rslib, rsbuild and rspack are supposed to be lightweight, to be a lot simpler than webpack. So, I wouldn't add more parameters but remove `-c` as well. Try to keep it simple.

**Comment by Timeless0911** [comment]
`-c` parameter should be preserved since config file can be named like `rslib.build.config.ts` just like `tsconfig.build.json`, and I totally agree to not add any other parameters to make things complexed. 

I think we can optimize the logic of finding `package.json` to handle most of situations but not all.

**Comment by binarykitchen** [comment]
@Timeless0911 Ok, good. Invite me for the code review, happy to throw in some ideas maybe.
