### ISSUE TITLE
[Bug]: extension of js request is not correct when using `autoExtension: false` along with `output.filename.js`

### ISSUE THREAD

**Issue by xc2** [web-infra-dev/rslib#362]
### Version

```

  System:
    OS: macOS 15.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 79.05 MB / 32.00 GB
    Shell: 3.7.1 - /opt/homebrew/bin/fish
  Browsers:
    Chrome: 130.0.6723.92
    Safari: 18.1
  npmPackages:
    @rslib/core: ^0.0.15 => 0.0.15
```

### Details

Cannot even set output.filename.js when `autoExtension` is `false`

## Setup

**package.json  of workspace**

```json
{ "type": "module" }
```

**rslib.config.ts**

```ts
// ...
  format: 'esm',
  autoExtension: false,
  output: {
    filename: {
      js: '[name].mjs'
    }
  }
// ...
  format: 'cjs',
  autoExtension: false,
  output: {
    filename: {
      js: '[name].cjs'
    }
  }
// ...
```

## Exepected

- `import xxx from './fooo.mjs'` in esm output
- `aaa_require('./fooo.cjs')` in cjs output

## But got

- `import xxx from './fooo.js'` in esm output
- `aaa_require('./fooo.js')` in cjs output

### Reproduce link

https://github.com/xc2/jbpr/blob/auto-extension-repro/sources/BUILD.ts

### Reproduce Steps

ESM:

run `pnpm rslib build -- //sources:esm` and look into `dist/lib`

CJS:

run `pnpm rslib build -- //sources:cjs` and look into `dist/lib`

**Comment by fi3ework** [comment]
Supposed to be a bug here https://github.com/web-infra-dev/rslib/blob/2e8b298c4bad888f3e923a1e17b5558944017dc5/packages/core/src/config.ts#L890. User's explicit relative import extension is not repected.

**Comment by xc2** [comment]
If the template filename is too complicated to determine the js extension, I’d prefer an option like `jsExtension: string | "auto"`

**Comment by Timeless0911** [comment]
We can add a `redirect.extension` configuration to handle this scene which is in our plan.
