### ISSUE TITLE
[Feature]: named config and positive filter

### ISSUE THREAD

**Issue by xc2** [web-infra-dev/rslib#382]
### What problem does this feature solve?

To build with specific lib configs (aka environment) only. For example, a library has 5 lib configs:

1. esm build with modern syntax
2. cjs build with modern syntax
3. esm build with legacy syntax
4. dts build
5. other package files

and only 1 or 2 is useful for development/test. we can filter out the others

### Rslib Config

```ts
{
  "lib": [
    { "name": "x", ... },
    { "name": "y", ... },
    { "name": "z", ... },
    { ... },
    { ... },
  ]
}
```

### Rslib CLI

```
--only x --only y
--only x,y
```

### Rsbuild

```ts
createRsbuild({
  rsbuildConfig: {
    environments: {
      x: { ... },
      y: { ... },
      z: { ... },
      esm0: { ... },
      esm1: { ... },
    }
  },
  environment: args.only
}
```

**Comment by fi3ework** [comment]
Nice suggestion. Today, we are adding similar functionality to [this pull request](https://github.com/web-infra-dev/rslib/pull/349). It will work like `rslib dev mf --lib a --lib b`, and the `--lib` parameter can be expanded to the build command, as described here.

Currently, Rslib is based on Rsbuild environments, which follow a default naming convention. You can find the code [here](https://github.com/web-infra-dev/rslib/blob/eaa07c8199a6ebc1eacc8f910b9b0bc7ee31a524/packages/core/src/config.ts#L1219). If there is only one ESM component, it will be named `esm`. If there are multiple environments, they will be named `esm1`, `esm2`, and so on. We initially chose `format` as the prefix for convenience in testing, but I think we should reconsider whether this is a good naming convention (it seems acceptable so far).

Using `"name"` as a explicit way to name environments is a good idea. My only concern is that this field is quite common while may only be necessary in specific situations (just personal feeling).

**Comment by xc2** [comment]
> My only concern is that this field is quite common while may only be necessary in specific situations (just personal feeling).

`"id"` as a neutral alternative

**Comment by Timeless0911** [comment]
filter is supported now, we should work on name field now.
