### ISSUE TITLE
[Bug]: Nothing exports from esm barrel exports files (bundleless mode)

### ISSUE THREAD

**Issue by xc2** [web-infra-dev/rslib#384]
### Version

```

  System:
    OS: macOS 15.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 81.77 MB / 32.00 GB
    Shell: 3.7.1 - /opt/homebrew/bin/fish
  Browsers:
    Chrome: 130.0.6723.92
    Safari: 18.1
  npmPackages:
    @rslib/core: ^0.0.16 => 0.0.16

```

### Details

There's no `export` statement found in the esm output of barrel exports files.

E.g.

source: https://github.com/xc2/barrel-mjs-repro/blob/main/src/barrel.js
output: https://github.com/xc2/barrel-mjs-repro/blob/main/dist/barrel.js
usage:
- node: https://github.com/xc2/barrel-mjs-repro/blob/main/node-test.js
- bun: https://github.com/xc2/barrel-mjs-repro/blob/main/package.test.js

### Reproduce link

https://github.com/xc2/barrel-mjs-repro

### Reproduce Steps

```sh
bun run --bun build:rslib
bun test
node node-test.js
```

**Comment by fi3ework** [comment]
Adding this to package.json

```json
  "pnpm": {
    "overrides": {
      "@rspack/core": "1.1.0"
    }
  }
```

will fix the bug. Export star from external files fixing PR are landed in 1.1.0. So an override is required (I don't know much about Bun, I tested it using pnpm :P )

The barrel file would be like:

```js
import "./foo.js";
export * from "./foo.js";
 // CONCATENATED MODULE: ./src/barrel.js
```

The first line should be striped as a known issue, still under working.

But this reproduction recalls me that: Rslib relies on a minimal version of `@rspack/core` among ^1.0.0, but it's prone to not be the latest enough. We might need to check @rspack/core version inside Rslib preflight, and throw some warning/error to user.

**Comment by xc2** [comment]
Thank you @fi3ework , will try it today

**Comment by xc2** [comment]
It works as expected with rspack 1.1.0
