### ISSUE TITLE
[Bug]: wrong tsconfig.json#paths output when `bundle: false`

### ISSUE THREAD

**Issue by carlosmfreitas2409** [web-infra-dev/rslib#407]
### Version
```
Rslib 0.0.16
```

### Details

When using `bundle: false`, the TS path aliases are not being correctly generated in the build.
When using `bundle: true`, it generates correctly, but it is not what I want.

- tsconfig.json
```json
{
  "extends": "@repo/tsconfig/react.json",
  "include": ["src", "stories"],
  "compilerOptions": {
    "paths": {
      "@/*": ["./src/*"]
    }
  }
}
```

- rslib config
![Image](https://github.com/user-attachments/assets/bc5b0da5-a95f-4a2d-a550-063ea5f222b8)

- rslib output
![Image](https://github.com/user-attachments/assets/e3e20b29-90f1-478c-87c9-185244d8dcd9)

- build script
`rslib build`

**Comment by fi3ework** [comment]
Since the request is externalized, it won't follow Rsbuild's default alias behavior(https://rsbuild.dev/guide/advanced/alias). It's better to be aligned.

**Comment by carlosmfreitas2409** [comment]
Hi @fi3ework.

Sorry, I didn't quite understand what you meant.
Are you saying to use `source.alias` and `source.aliasStrategy` in rslib config?
If so, I've tried using them too, but it didn't change anything.

**Comment by fi3ework** [comment]
`source.alias` or `source.aliasStraategy` won't make it work. The alias to an source path (which means it's dynamic after resolved) need `getResolve` function https://github.com/web-infra-dev/rslib/issues/238#issuecomment-2376536224.

**Comment by Timeless0911** [comment]
https://github.com/web-infra-dev/rspack/pull/7348 external function `getResolve` will be supported after this pr merged.

**Comment by yf-yang** [comment]
Sorry, I cannot keep up with your terminology. Does this mean that _when using path aliases and building bundless DTS, the aliases would be replaced with the correct relative paths_ after https://github.com/web-infra-dev/rspack/pull/7348 is done?

**Comment by Timeless0911** [comment]
> Does this mean that when using path aliases and building bundless DTS, the aliases would be replaced with the correct relative paths after https://github.com/web-infra-dev/rspack/pull/7348 is done?

For bundleless DTS, the alias redirect should be another issue, tracking in https://github.com/web-infra-dev/rslib/issues/409

**Comment by noshower** [comment]
> Since the request is externalized, it won't follow Rsbuild's default alias behavior(https://rsbuild.dev/guide/advanced/alias). It's better to be aligned.

you can use https://github.com/noshower/ts-paths-to-relative-path-rspack-plugin

**Comment by Timeless0911** [comment]
> this plugin can convert ts paths alias to relative paths

 #535 will solve this issue in Rslib internally.
