### ISSUE TITLE
[Feature]: Support default extension alias

### ISSUE THREAD

**Issue by fi3ework** [web-infra-dev/rslib#41]
### What problem does this feature solve?

The following code 

```js
// ./src/main.js
import { v } from './foo.js'

// ./src/foo.ts
export v = 1
```

will panic for Rslib as it can't resolve `./foo.js` by default. But it should work when using `moduleResolution: 'nodenext'`. Considering enable default or heuristic `extensionAlias` https://webpack.js.org/configuration/resolve/#resolveextensionalias.

esbuild supports this by default, which might be too loose somehow.

**Comment by Timeless0911** [comment]
what esbuild do: https://github.com/evanw/esbuild/blob/332727499e62315cff4ecaff9fa8b86336555e46/internal/resolver/resolver.go#L1659-L1681

**Comment by Timeless0911** [comment]
I think we can add `extensionAlias` like https://github.com/webpack/webpack/issues/13252#issuecomment-1824282100
