### ISSUE TITLE
[Bug]: Module is empty when it is another entry module

### ISSUE THREAD

**Issue by colinaaa** [web-infra-dev/rslib#452]
### Version

```sh
System:
    OS: macOS 14.6.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 14.12 GB / 96.00 GB
    Shell: 3.7.1 - /opt/homebrew/bin/fish
  Browsers:
    Chrome: 130.0.6723.117
    Safari: 17.6
  npmPackages:
    @rslib/core: ^0.0.18 => 0.0.18
```

### Details

I'm building an library using Rslib with multiple entries:

```js
import { defineConfig } from '@rslib/core';

export default defineConfig({
  lib: [
    {
      format: 'esm',
      syntax: 'es2021',
    },
  ],
  source: {
    entry: {
      index: './src/index.ts',
      foo: './src/foo.ts',
    },
  },
});
```

And `index` is using `foo` as dependencies:

```js
// index.js
import { foo } from './foo.js'
console.log(foo)
```

But this results in get an empty module `./src/foo.ts` in `dist/index.js`:

```js
// dist/index.js
var __webpack_modules__ = {
    "./src/foo.ts": function() {}
};
```

which would cause error at runtime.

### Reproduce link

https://github.com/colinaaa-reproductions/rslib-repro-multi-entries

### Reproduce Steps

1. `pnpm install`
2. `pnpm build`
3. `node dist/index.js`

An error occurs:

```
console.log((0, foo.foo)());
                        ^

TypeError: (0 , foo.foo) is not a function
    at /root/dist/index.js:22:25
    at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)
```

**Comment by fi3ework** [comment]
Do you expect `foo` is shared between `dist/foo.js` and `dist/index.js`?

Sharing modules could break ESM and it's a known issue. We might support non-sharing mode (like turn of https://esbuild.github.io/api/#splitting in esbuild) in short time to make sure the output is correct at least.

---

Also ref multiple entry module issue https://github.com/web-infra-dev/rslib/issues/316.

**Comment by colinaaa** [comment]
> Do you expect `foo` is shared between `dist/foo.js` and `dist/index.js`?

For now, no.
