### ISSUE TITLE
[Bug]: Unable to generate bundle DTS

### ISSUE THREAD

**Issue by puiks** [web-infra-dev/rslib#506]
### Version

```sh
System:
    OS: macOS 14.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 53.56 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 131.0.6778.86
    Edge: 131.0.2903.70
    Safari: 17.3.1
  npmPackages:
    @rslib/core: ^0.1.1 => 0.1.1
```

### Details

I install the `@microsoft/api-extractorset` and set the `dts.bundle` to true, then execute `rslib build`, the DTS build is failed and the error is below
```
error   API Extractor Error
error   Internal Error: Unable to analyze the export "default" in /Users/****/node_modules/@types/react/index.d.ts
```

This is my code
```
import React from "react";

export interface IDemo {
  name: string;
  age: number;
}

export function Demo() {
  const demo1: IDemo = {
    name: "demo1",
    age: 20,
  };

  return <div>{demo1.name}</div>;
}

```
Here is my rslib config
```
import { defineConfig } from "@rslib/core";
import { pluginReact } from "@rsbuild/plugin-react";

export default defineConfig({
  lib: [
    {
      format: "cjs",
      dts: {
        bundle: true,
      },
    },
  ],
  plugins: [pluginReact()],
  output: {
    cleanDistPath: true,
    target: "web",
    sourceMap: true,
  },
});
```

### Reproduce link

*

### Reproduce Steps

Execute rslib build

**Comment by Timeless0911** [comment]
This should be an issue related to api-extractor, similar to https://github.com/microsoft/rushstack/issues/3374. Maybe bundle `@types/react` is hard to api-extractor 😂

**Comment by puiks** [comment]
> This should be an issue related to api-extractor, similar to [microsoft/rushstack#3374](https://github.com/microsoft/rushstack/issues/3374). Maybe bundle `@types/react` is hard to api-extractor 😂

Well... It seems like bundle DTS cannot work with react. Is there any where to skip bundling`@types/react` or some kind of complex dependencies types ?

**Comment by Timeless0911** [comment]
`autoExternal` is enabled by default, so all `devDependencies` will be bundled. You can add `@types/react` to `output.externals` to externalize it.
