### ISSUE TITLE
[Bug]: rslib run storybook can't parse *.less file and *jsx file

### ISSUE THREAD

**Issue by shimingw** [web-infra-dev/rslib#530]
### Version

```sh
System:
    OS: macOS 14.6
    CPU: (8) arm64 Apple M3
    Memory: 258.08 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 131.0.6778.109
    Safari: 17.6
  npmPackages:
    @rslib/core: ^0.1.2 => 0.1.2
```

## first problem
when i run `pnpm dev` or `pnpm build`, i can run correctly. even i create a new project  by rslib , i alose get this error
but when i run `pnpm storybook` or `pnpm build:storybook`, i get a less-loader error, like this
![Image](https://github.com/user-attachments/assets/d88d1c4a-ebe3-4bd7-a78f-d8718dc1a170)

## second problem
if i use .jsx extension file, i will got a error, like this, even i create a new project by rslib and use javascript , i alose get this error
![Image](https://github.com/user-attachments/assets/d87c673d-61b6-4df0-ad10-17e927781c91)

### Reproduce link

none

## first problem
1. create a new project, use .less extension file, and add @rsbuild/plugin-less
2. execute `pnpm storybook`
3. you will get the error

## second proble
1. create a new prkect and use javascript and jsx
2. execute `pnpm storybook`
3. you will get the error

**Comment by shimingw** [comment]
> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to help us address the issue, we cannot assist with troubleshooting based on the information currently provided. Thanks.
> 
> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

https://github.com/shimingw/rslib-bug-report/tree/main/rslib-project-demo

this demo can recurrent the problem, when you run command `pnpm storybook`. you will see.

**Comment by fi3ework** [comment]
1. Follow the [document](https://storybook-rsbuild.netlify.app/guide/integrations/rslib.html), configure the project correctly. You can check the example https://github.com/rspack-contrib/storybook-rsbuild/blob/main/sandboxes/rslib-react-component/.storybook/main.ts here.
2. Add `react-dom` to 18.3.1 to the dev dependencies.

**Comment by shimingw** [comment]
sorry, i forgot push my .storybook folder, now, i had update my storybook/main.ts file. and update my dependency base on your example ：https://github.com/rspack-contrib/storybook-rsbuild/blob/main/sandboxes/rslib-react-component/package.json.
but, wo got a new error. i had update my reproduction:https://github.com/shimingw/rslib-bug-report/tree/main/rslib-project-demo
<img width="1277" alt="Image" src="https://github.com/user-attachments/assets/89f74fb8-5aac-4d77-8431-6bedfe318456" />

**Comment by Timeless0911** [comment]
You should update these packages 
![Image](https://github.com/user-attachments/assets/58621c29-56a1-47c5-a55f-ef889fe2df1e)

**Comment by shimingw** [comment]
> You should update these packages ![Image](https://github.com/user-attachments/assets/58621c29-56a1-47c5-a55f-ef889fe2df1e)

thank you, it's worked.
