### ISSUE TITLE
[Bug]: alias configuration does not take effect

### ISSUE THREAD

**Issue by Lisheri** [web-infra-dev/rslib#553]
### Version

```sh
System: macos14.3.1
npmPackages: pnpm
Rslib 0.1.12
```

### Details

rslib.config.ts

```ts
import { defineConfig } from '@rslib/core';
import { pluginVue } from '@rsbuild/plugin-vue';
import { pluginVueJsx } from '@rsbuild/plugin-vue-jsx';
import { pluginBabel } from '@rsbuild/plugin-babel';

export default defineConfig({
  resolve: {
    alias: {
      '@': './src'
    }
  },
  source: {
    entry: {
      index: ['./src/**']
    }
  },
  lib: [
    {
      bundle: false,
      dts: true,
      format: 'esm'
    }
  ],
  output: {
    target: 'web'
  },
  plugins: [
    pluginBabel({
      include: /\.(?:jsx|tsx)$/
    }),
    pluginVue(),
    pluginVueJsx()
  ],
  tools: {
    rspack: {
      plugins: [
        require('unplugin-vue-macros/rspack')({
          // 覆盖插件选项
          vue: pluginVue(),
          vueJsx: pluginVueJsx()
        })
      ]
    }
  }
});
```

tsconfig.json

```json
{
  "compilerOptions": {
    "lib": ["DOM", "ES2021"],
    "module": "ESNext",
    "jsx": "preserve",
    "jsxFactory": "h",
    "jsxFragmentFactory": "Fragment",
    "strict": true,
    "skipLibCheck": true,
    "isolatedModules": true,
    "resolveJsonModule": true,
    "moduleResolution": "bundler",
    "useDefineForClassFields": true,
    "target": "esnext",
    "baseUrl": ".",
    "noImplicitAny": false,
    "types": ["unplugin-vue-macros/macros-global"],
    "paths": {
      "@/*": [
        "./src/*"
      ]
    },
  },
  "vueCompilerOptions": {
    "plugins": ["unplugin-vue-macros/volar"],
  },
  "include": ["src/**/*.ts", "src/**/*.d.ts", "src/**/*.tsx", "src/**/*.vue"],
}
```

origincode
![Image](https://github.com/user-attachments/assets/2e4875f0-b333-4ee7-a693-985a427b88a1)

after build
![Image](https://github.com/user-attachments/assets/5bd14167-e4e8-4382-b9ad-9301d485932b)

after building, the path alias is not processed

### Reproduce link

https://github.com/Lisheri/rslib_vue_components

### Reproduce Steps

pnpm i
pnpm build
see dist/index.js

**Comment by Timeless0911** [comment]
In bundleless mode, it should be `externals` not `alias` issue, see https://lib.rsbuild.dev/config/rsbuild/resolve#resolvealias.

We will processing path redirection in https://github.com/web-infra-dev/rslib/pull/535.

**Comment by Lisheri** [comment]
ok
But what I need is to process local path mapping, and do not need to deal with external dependency paths. When I enable bundle mode, the following error is directly triggered. Is it related to the above issue?

![Image](https://github.com/user-attachments/assets/70a0803e-6bac-4c14-86c9-9b480b00fd23)

Reproduce link unchanged

**Comment by Timeless0911** [comment]
In bundle mode, you should set entry to `./src/index.tsx`.

**Comment by chenjiahan** [comment]
> In bundle mode, you should set entry to ./src/index.tsx.

We can add a pre-check for this to provide better error diagnostics
