### ISSUE TITLE
[Bug]: Cannot import typings from @rslib/core

### ISSUE THREAD

**Issue by patricklafrance** [web-infra-dev/rslib#567]
### Version

```sh
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i7-13700H
    Memory: 8.66 GB / 31.62 GB
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

### Details

I cannot import a config type like `EcmaScriptVersion` from `@rslib/core`.

Example:

```ts
import { type EcmaScriptVersion } from "@rslib/core";
```

I get the following error: _"Module '"@rslib/core"' has no exported member 'EcmaScriptVersion'.ts(2305)"_

![Image](https://github.com/user-attachments/assets/0487b2e1-9a09-4844-a9a4-c9036bbd975d)

Now, If I go into my local `node_modules` directory and update the source code of the `@rslib/core` package I can get it to work, byy updating the `node_modules/@rslib/core/dist-types/types/index.d.ts` file.

Before:

```ts
export type * from "./config";
export type * from './utils';
```

Now:

```ts
export type * from './config/index.d.ts';
export type * from './utils';
```

Now I can import the type:

![Image](https://github.com/user-attachments/assets/06837e97-27c2-49cb-a3fa-3333751d1faa)

I am using Typescript `5.5.4` and my `tsconfig.json` file is:

```json
{
    "$schema": "https://json.schemastore.org/tsconfig",
    "compilerOptions": {
        "allowImportingTsExtensions": true,
        "moduleResolution": "NodeNext",
        "module": "NodeNext",
        "target": "ESNext",
        "lib": ["dom", "dom.iterable", "esnext"],

        "isolatedModules": true,
        "allowSyntheticDefaultImports": true,
        "resolveJsonModule": true,

        "strict": true,

        "allowJs": true,
        "checkJs": false,

        "esModuleInterop": true,
        "skipLibCheck": true,
        "forceConsistentCasingInFileNames": true,

        "noEmit": true,
        "sourceMap": false,

        "jsx": "react-jsx"
    }
}
```

Thanks for your help!

Patrick

### Reproduce link

https://github.com/patricklafrance/rslib-import-config-types

### Reproduce Steps

```ts
import { type EcmaScriptVersion } from "@rslib/core";
```

**Comment by Timeless0911** [comment]
Got it, this is related to moduleResolution, I will fix this soon

**Comment by patricklafrance** [comment]
Thank you @Timeless0911 🙏🏻
