### ISSUE TITLE
[Bug]:  jsxFactory设置为了h  ，但是编译后的文件依然使用了React.createElement

### ISSUE THREAD

**Issue by NexxLuo** [web-infra-dev/rslib#574]
### Version

```sh
windows 10;
Chrome;
@rslib/core 0.1.3;
```

### Details

1. tsconfig.json配置如下：
 ```
{
    "extends": "../../tsconfig.json",
    "compilerOptions": {
      "jsxFactory": "h",
      "rootDir": "src",
      "isolatedModules":true,
      "declaration": true
    },
    "include": ["src"]
  }
  
```

2. 项目中使用vue2以及jsx编写组件，使用pluginVue2、pluginVue2Jsx对文件进行编译，编译后的文件使用了`React.createElement`而不是`h`函数
3. `rslib.config.ts`配置：
```javascript
import { defineConfig } from "@rslib/core";
import { pluginSass } from "@rsbuild/plugin-sass";
import { pluginVue2 } from "@rsbuild/plugin-vue2";
import { pluginVue2Jsx } from "@rsbuild/plugin-vue2-jsx";

export default defineConfig({
  plugins: [pluginSass(),pluginVue2(),pluginVue2Jsx()],
  lib: [
    {
      source: {
        entry: {
          index: "./src/**",
        },
      },
      format: "cjs",
      bundle: false,
      autoExternal:false,
      dts: { bundle: false, distPath: "./lib", build: false, abortOnError: false },
      //dts:false
    }
  ],
  output: {
    target: "web",
    distPath: {
      root: "./lib",
    },
  }
});

```

4. 源文件及编译后的文件内容如下：
源文件：
![Image](https://github.com/user-attachments/assets/9d9d6f83-40fb-4435-ac7d-9aa2fbb5d939)

编译后的结果：

![Image](https://github.com/user-attachments/assets/20dc52b8-8143-40aa-9464-731d6e61c1fe)

### Reproduce link

https://github.com/NexxLuo/rslib-demo.git

### Reproduce Steps

1. yarn install
2. npm run build
3. 查看packages/packages-a/lib/ComponentA.js，文件中错误使用了`React.createElement`

**Comment by NexxLuo** [comment]
需要添加配置` pluginBabel({
      include: /\.(?:jsx|tsx)$/,
    })`才行，这是为什么？

**Comment by fi3ework** [comment]
It's documented here https://github.com/rspack-contrib/rsbuild-plugin-vue2-jsx

> Since the Vue JSX plugin relies on Babel for compilation, you need to additionally add the [@rsbuild/plugin-babel](https://www.npmjs.com/package/@rsbuild/plugin-babel).

> Babel compilation will introduce extra overhead, in the example above, we use include to match .jsx and .tsx files, thereby reducing the performance cost brought by Babel.

I believe the need to manually add babel requirements is to minimize the impact scope of babel for performance reasons.
