### ISSUE TITLE
[Bug]: Multiple export (entry points)

### ISSUE THREAD

**Issue by alefduarte** [web-infra-dev/rslib#575]
### Version

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 9.34 GB / 31.67 GB
  Browsers:
    Edge: Chromium (127.0.2651.86)
    Internet Explorer: 11.0.19041.4355

demo:
  System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (2) x64 AMD EPYC
    Memory: 1.41 GB / 4.01 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
```

### Details

I'm creating a simple library with multiple entries.
I have seen this: https://github.com/web-infra-dev/rsbuild/discussions/3702
But it still does not answer my question.
I want to import my components like this:
``` js
import { Button } from '@acme/ui/Inputs';
```
However, this doesn't work. I've managed to get it working using Vite and Rollup, but I want to migrate to rslib instead. 
I'm likely making a mistake, but I can't find any documentation on how to resolve it.

My entries are set up as follows:
``` js
  source: {
    entry: {
      './Inputs': 'src/Inputs/index.ts',
      './Surfaces': 'src/Surfaces/index.ts',
    },
  },
```
I'm also receiving this warning:
> duplicate entry: index, this may lead to the incorrect output, please rename the file
My exports configuration is:
``` json
  "exports": {
    "./Inputs": {
      "types": "./dist/Inputs/index.d.ts",
      "import": "./dist/index.js"
    },
    "./Surfaces": {
      "types": "./dist/Surfaces/index.d.ts",
      "import": "./dist/index.js"
    }
  },
```
I know the import is the same path because there is only one js file, I don't know why.
I've created a working example, which you can find here: 
https://codesandbox.io/p/devbox/sx9t7q

Ultimately, I want to be able to import components in this way:
``` js
import { Button } from '@acme/ui/Inputs';
import { Card } from '@acme/ui/Surfaces';
```

### Reproduce link

https://codesandbox.io/p/devbox/sx9t7q

### Reproduce Steps

1. run `pnpm i` to install all dependencies
2. run `pnpm build` to build all packages
alternatively, run `pnpm build --filter=@acme/ui` to build only the ui package.

**Comment by Timeless0911** [comment]
Try to set `bundle: true`, see https://lib.rsbuild.dev/config/lib/bundle#bundle-true

**Comment by alefduarte** [comment]
I changed it and made some updates to the bundle and it worked! I failed to understand what it meant in the documentation. Thank you for the help!
