### ISSUE TITLE
[Bug]: dts not covert alias path

### ISSUE THREAD

**Issue by liuwenzhuang** [web-infra-dev/rslib#586]
### Version

```sh
System:
    OS: Linux 6.1 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (2) x64 AMD EPYC
    Memory: 2.59 GB / 4.01 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  npmPackages:
    @rslib/core: ^0.1.5 => 0.1.5
```

### Details

![Image](https://github.com/user-attachments/assets/eeada466-3024-42f1-9a7b-b6d040ac6074)

### Reproduce link

https://codesandbox.io/p/devbox/rslib-dts-alias-not-covert-s4ytcm

### Reproduce Steps

1. `npm run build`
2. see `dist/index.d.ts`

**Comment by Timeless0911** [comment]
Duplicate of #409 , we will support `redirect.dts` in the near future.
