### ISSUE TITLE
[Bug]: Conflict: Multiple assets emit different content when using source.assetsInclude

### ISSUE THREAD

**Issue by NexxLuo** [web-infra-dev/rslib#614]
### Version

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 14.88 GB / 31.22 GB
  Browsers:
    Edge: Chromium (128.0.2739.67)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    @rslib/core: ^0.2.0 => 0.2.0
```

### Details

Error will occur when using `source.assetsInclude`

![Image](https://github.com/user-attachments/assets/aabd2569-3827-4a83-84a8-282c7b559909)

### Reproduce link

https://github.com/NexxLuo/rslib-demo.git

### Reproduce Steps

1. execute `yarn install` in root dir
2. execute `npm run build` in package-a
3. check the error output in the console

**Comment by NexxLuo** [comment]
> Do you want to keep the `.scss` file in the original directory without processing it or put it in the `static/assets` folder as a static resource? Which one?

I want to copy to lib folder and without processing . just like this https://github.com/web-infra-dev/rslib/discussions/478

**Comment by Timeless0911** [comment]
You do not need to do add `pluginSass({ exclude: /.scss/})` and `assetsInclude: /\.scss$/`.

The best way to avoid transform less\scss to css in bundleless mode is:

```ts
lib: [
  {
    source: {
      entry: {
        index: ["./src/**", "!src/**/*.scss"],
      },
    },
    output: {
      copy: [{ from: "**/*.scss", context: path.join(__dirname, "src") }],
    },
    redirect: {
      style: false,
    },
  },
],
```

1. Set `source.entry` to ignore `scss` file
2. Set `output.copy` to copy `scss` file to output folder
3. Set `redirect.style` to `false` to disable redirecting the import path of the style file

**Comment by NexxLuo** [comment]
It works, thanks
