### ISSUE TITLE
[Bug]: The import path points to node_modules incorrectly

### ISSUE THREAD

**Issue by NexxLuo** [web-infra-dev/rslib#616]
### Version

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 14.88 GB / 31.22 GB
  Browsers:
    Edge: Chromium (128.0.2739.67)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    @rslib/core: ^0.2.0 => 0.2.0
```

### Details

When importing a package, the import path in the generated file is incorrect, and the path points to `node_modules` incorrectly.

1. source file

![Image](https://github.com/user-attachments/assets/457209a7-c7ac-4d5d-a651-ffc6a1320b4b)

2. after compilation

![Image](https://github.com/user-attachments/assets/c61f1b40-e8cf-4403-b257-64f97ed94f1c)

### Reproduce link

https://github.com/NexxLuo/rslib-demo.git

### Reproduce Steps

1. execute `yarn install` in root dir
2. execute `npm run build`  in package-b
3. check the file after compilation

**Comment by Timeless0911** [comment]
Why incorrect? Your `node_modules` is just in `../../../`.

**Comment by Timeless0911** [comment]
You disable `autoExternal` and do not specify `dayjs` in `dependencies` field in `package.json`, thus we can not judge whether to externalize this package. 

You can remove `autoExternal: false` and correctly specify `dayjs` in `dependencies` field now.

May be we should deal with this phantom dependencies situation to detect whether a module is resolved to `node_modules`.

**Comment by NexxLuo** [comment]
Import a phantom dependency is a common situation.Maybe it is necessary to solve this problem.

**Comment by Timeless0911** [comment]
> Import a phantom dependency is a common situation.Maybe it is necessary to solve this problem.

You can configure `output.external` yourself.

**Comment by NexxLuo** [comment]
I think as an npm package building tool, this feature should be supported by default instead of complex configuration, looking forward to the new version.
