### ISSUE TITLE
[Bug]: Cannot share context api

### ISSUE THREAD

**Issue by alefduarte** [web-infra-dev/rslib#627]
### Version

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 4.06 GB / 31.67 GB
  Browsers:
    Edge: Chromium (127.0.2651.86)
    Internet Explorer: 11.0.19041.4355
```

### Details

I created a context like so
``` ts
import { createContext, useState } from 'react';

interface ThemeContextType {
  theme: 'light' | 'dark';
  toggleTheme: () => void;
}

export const ThemeContext = createContext<ThemeContextType>({} as ThemeContextType);

export const ThemeProvider = ({
  children,
}: Readonly<{ children: React.ReactNode }>) => {
  const [theme, setTheme] = useState<'light' | 'dark'>('light');

  const toggleTheme = () => {
    setTheme((prevTheme) => (prevTheme === 'light' ? 'dark' : 'light'));
  };

  return (
    <ThemeContext.Provider value={{ theme, toggleTheme }}>
      {children}
    </ThemeContext.Provider>
  );
};
```

and a consumer:
``` ts
import { useContext } from 'react';
import { ThemeContext } from './ThemeContext';

export default function ToggleTheme() {
  const { theme, toggleTheme } = useContext(ThemeContext);
  const handleSwitch = () => {
    toggleTheme();
  };

  return (
    <div>
      Current theme: {theme}
      <button onClick={handleSwitch}>Toggle</button>
    </div>
  );
}
```

I export both using the bundle option.

``` ts
import { pluginReact } from '@rsbuild/plugin-react';
import { defineConfig } from '@rslib/core';

export default defineConfig({
  source: {
    entry: {
      './context': './src/ThemeContext.tsx',
      './ToogleTheme': './src/ToogleTheme.tsx'
    },
  },
  lib: [
    {
      bundle: true,
      dts: true,
      format: 'esm',
      output: { externals: { react: 'react', 'react-dom': 'ReactDOM' } },
    },
  ],
  output: {
    target: 'web',
  },
  plugins: [pluginReact()],
});
```

In another app, I inject it in the root
``` ts
root.render(
    <React.StrictMode>
      <ThemeProvider>
        <App />
      </ThemeProvider>
    </React.StrictMode>,
  );
```
and inside App, I import ToggleTheme

``` ts
const App = () => {
  return (
    <div className="content">
      <h1>Rsbuild with React</h1>
      <p>Start building amazing things with Rsbuild.</p>
      <ToogleTheme />
    </div>
  );
};
```

But the context is empty, the state is undefined.

This used to work fine with vite and rollup. Is there anything else I should do?
I have a working example: https://codesandbox.io/p/devbox/sx9t7q

### Reproduce link

https://codesandbox.io/p/devbox/sx9t7q

### Reproduce Steps

1. run `pnpm i` to install all dependencies
1. run `pnpm build --filter=@acme/ui` to build only the ui package.
1. go to the app folder `cd apps/app`
1. run `pnpm dev`
 
 
running `pnpm dev --filter=@acme/app` at the root gave me errors, I think it has something to do with the sandbox.

**Comment by fi3ework** [comment]
The following modifications can help you correctly build the npm package:

1. Modify the entry and use the bundleless mode:
```ts
export default defineConfig({
  source: {
    entry: {
      index: ['./src/**']
    },
  },
```
2. Adjust the `exports` mapping:
```json
"./context": {
  "types": "./dist/ThemeContext.d.ts",
  "import": "./dist/ThemeContext.js"
},
```
When using the bundle mode, Rslib currently does not support ESM format for split chunks, and split chunks are disabled by default. This can cause the context to fail to access the same instance, leading to the error mentioned in the issue. Generally, when building npm packages, the bundleless mode is used, which allows the build tool to perform tree shaking more effectively and ensures the singleton pattern.
